import React from "react";
import { Row, Col } from "react-bootstrap";
import {DisplayCard} from "../components/DisplayCard";
import ReportsForm from "../views/reports/ReportsForm";
import ReportsTable from "../views/reports/ReportsTable";

export default function ReportsPage() {
  return (
    <>
      <Row>
        <Col lg={8}>
          <DisplayCard title="Reports" subtitle="Last 3 reports generated by system">
            <ReportsTable />
          </DisplayCard>
        </Col>
        <Col lg={4}>
          <ReportsForm/>
        </Col>
      </Row>
    </>
  );
}
